### ISSUE TITLE
Multi-container volume use

### ISSUE THREAD

**Issue by obr-09** [cloudposse/goofys#4]
When using docker/docker-compose, I don't necessarily want to create an image using this one as source, but would rather like to use a same volume across multiple containers.  

Using an external volume created with local driver does not work, I assumed some driver plugins would work and will try some. This is however a rather common use case I think, and it would be very useful to include something about this within the documentation (having an example docker-compose.yml could also be a very useful and practical way to show that use).

Thanks for the image!

**Comment by obr-09** [comment]
I managed to share a volume between containers, the solution was quite simple.  

I created the volume directly in the goofys service part of the docker-compose.yml with "shared": "/home/random/path:/mnt/s3:shared"
On other containers, I added the same volume path without the "shared" path.  

However, I have issues reading the volume content because of the user set to root:root. I would like to add the option to set the uid/gid.
I would gladly create a PR, but I noticed the Github repository looked quite outdated as it is... (#5)

**Comment by osterman** [comment]
@zessirb thanks for reporting back your solution. Use, the key is to use `:shared`. If you want to contribute this to the example, please share and we'll review promptly.

Also, you're invited to join our slack community here: https://slack.sweetops.com/
