### ISSUE TITLE
Update Github to match DockerHub version

### ISSUE THREAD

**Issue by obr-09** [cloudposse/goofys#5]
I noticed the Github source code looks very different from the Dockerhub image. When pulling the repository and building the image myself, the "run.sh" script fails, indicating "goofys not found".  
When looking at the Docker Hub image detail, [commands look very different](https://hub.docker.com/layers/cloudposse/goofys/latest/images/sha256-85866a498f7edd6c269afce8a3d344467fe3a145d2a2c197031bb6a764dd1b9a)...  

Could it be possible to update the Github with a working version of the docker image? I'm not asking for a detailed versioning system, just sync between the last updated version and the Github repository so I can work on it.

**Comment by osterman** [comment]
Hrmmm maybe something is wrong with our automatic Docker builds on Docker hub. Will take a look. Thanks for reporting!

**Comment by osterman** [comment]
Travis builds have been fixed. Tagged a new image for `0.2.1` . Thanks for reporting!
